import { FormField } from "@/types/form/form";

export const OrnamentOpeningFields = (itemCollection: { label: string; value: string }[]): FormField[] => [
    {
        name: "itemId",
        label: "Item",
        type: "combobox",
        size: "sm",
        required: true,
        rounded: "sm",
        items: itemCollection , // ✅ collection from parent
        allowFocus: true,
    },
    {
        name: "pcs",
        label: "Pieces",
        type: "number",
        size: "sm",
        required: true,
        rounded: "sm",
    },
    {
        name: "grswt",
        label: "Gross Weight",
        type: "number",
        size: "sm",
        required: true,
        rounded: "sm",
        allowFocus: true,
        decimalScale:3,
    },
    {
        name: "netwt",
        label: "Net Weight",
        type: "number",
        size: "sm",
        required: true,
        rounded: "sm",
        allowFocus: true,
        decimalScale:3,
        disabled:true
    },
    {
        name: "touch",
        label: "Touch",
        type: "number",
        size: "sm",
        required: true,
        rounded: "sm",
        allowFocus: true,
        decimalScale:1,
    },
    {
        name: "purewt",
        label: "Pure Weight",
        type: "number",
        size: "sm",
        required: true,
        rounded: "sm",
        allowFocus: true,
        decimalScale:3,
        disabled:true
    },
    {
        name: "stnwt",
        label: "Stone Weight",
        type: "number",
        size: "sm",
        required: true,
        rounded: "sm",
        allowFocus: true,
        decimalScale:3,
    },
    {
        name: "openCash",
        label: "Open Cash",
        type: "number",
        size: "sm",
        required: true,
        rounded: "sm",
        allowFocus: true,
        decimalScale:2,
    },
    {
        name: "stnAmt",
        label: "Stone Amount",
        type: "number",
        size: "sm",
        required: true,
        rounded: "sm",
        allowFocus: true,
        decimalScale:2,
    },
];