import { FormField } from "@/types/form/form";

export const OrnamentOpeningFields = (itemCollection: { label: string; value: string }[]): FormField[] => [
    {
        name: "itemId",
        label: "ITEM",
        type: "combobox",
        size: "sm",
        required: true,
        rounded: "sm",
        items: itemCollection , // ✅ collection from parent
        allowFocus: true,
    },
    {
        name: "pcs",
        label: "PIECES",
        type: "number",
        size: "sm",
        required: true,
        rounded: "sm",
    },
    {
        name: "grswt",
        label: "GROSS WEIGHT",
        type: "number",
        size: "sm",
        required: true,
        rounded: "sm",
        allowFocus: true,
        decimalScale:3,
    },
    {
        name: "stnwt",
        label: "STONE WEIGHT",
        type: "number",
        size: "sm",
        required: true,
        rounded: "sm",
        allowFocus: true,
        decimalScale: 3,
    },
    {
        name: "netwt",
        label: "NET WEIGHT",
        type: "number",
        size: "sm",
        required: true,
        rounded: "sm",
        allowFocus: true,
        decimalScale:3,
        disabled:true
    },
    {
        name: "touch",
        label: "TOUCH",
        type: "number",
        size: "sm",
        required: true,
        rounded: "sm",
        allowFocus: true,
        decimalScale:1,
    },
    {
        name: "purewt",
        label: "PURE WEIGHT",
        type: "number",
        size: "sm",
        required: true,
        rounded: "sm",
        allowFocus: true,
        decimalScale:3,
        disabled:true
    },
    
    {
        name: "openCash",
        label: "OPEN CASH",
        type: "number",
        size: "sm",
        required: true,
        rounded: "sm",
        allowFocus: true,
        decimalScale:2,
    },
    {
        name: "stnAmt",
        label: "STONE AMOUNT",
        type: "number",
        size: "sm",
        required: true,
        rounded: "sm",
        allowFocus: true,
        decimalScale:2,
    },
];